### ISSUE TITLE
backend-error im apache error.log, shariff.json missing

### ISSUE THREAD

**Issue by niefra** [joomla-agency/plg_jooag_shariff#24]
hi,
I found this in my apache error-log

PHP Fatal error:  Uncaught exception 'Zend\\Config\\Exception\\RuntimeException' with message 'File 'shariff.json' doesn't exist or not readable' in .../plugins/system/jooag_shariff/backend/vendor/zendframework/zend-config/src/Reader/Json.php:39\nStack trace:\n
#0 .../plugins/system/jooag_shariff/backend/index.php(21): Zend\\Config\\Reader\\Json->fromFile('shariff.json')\n
#1 .../plugins/system/jooag_shariff/backend/index.php(26): Application::run()\n
#2 {main}\n
  thrown in .../plugins/system/jooag_shariff/backend/vendor/zendframework/zend-config/src/Reader/Json.php on line 39

I use the shariff-master plugin for joomla 3.5. same result with shariff version 2.10.

do I really need a shariff.json file? or is it enough, if I catch the exception?

best franz

**Comment by ufuk-avcu** [comment]
Hi. You need the json File for the Share Counter. Without this file, the PHP Sharif Backend don't knows how to count and handle the requests. I'm developing the new Version of the Shariff Plugin for Joomla in the 3.3.0 Branch, with the newest Shariff PHP Backend Version 5.2.0. Maybe with the newest Version, this problem is solved. Can you download and test the 3.3.0 Branch? Best regards.

**Comment by niefra** [comment]
thank you for the explanaition, i tried the new version and it worked, no more apache error.

best
franz

**Comment by ufuk-avcu** [comment]
Thank you for your feedback.
